#!/bin/sh /etc/rc.common
START=95
STOP=10
USE_PROCD=1

start_service() {
    local enabled
    config_load fakeflow
    config_get_bool enabled main enabled 0
    [ "$enabled" = 1 ] || return 0
    procd_open_instance
    procd_set_param command /usr/sbin/fakeflow run --config /etc/fakeflow.toml
    procd_set_param respawn 3600 5 5
    procd_set_param file /etc/fakeflow.toml
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param limits memlock="unlimited"
    procd_close_instance
}

reload_service() {
    local enabled
    config_load fakeflow
    config_get_bool enabled main enabled 0
    if [ "$enabled" != 1 ]; then
        stop
    elif /usr/sbin/fakeflow status >/dev/null 2>&1; then
        /usr/sbin/fakeflow reload
    else
        start
    fi
}

service_triggers() {
    procd_add_reload_trigger fakeflow
}
